/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.l2frame;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Марина
 */
public class l2frame extends javax.swing.JFrame { //наследование
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(l2frame.class.getName());
    private DefaultTableModel tableModel;
    private ArrayList<RecIntegral> dataList;
    /**
     * Creates new form l1frame
     */
    public l2frame() {
        initComponents();
        tableModel = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        dataList = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(153, 0, 204));

        jLabel1.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jLabel1.setText("Function: cos (x^2)");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.SE_RESIZE_CURSOR));

        jLabel3.setFont(new java.awt.Font("Sitka Small", 0, 12)); // NOI18N
        jLabel3.setText("Данные для интегрирования:");

        jLabel4.setFont(new java.awt.Font("Sitka Small", 0, 12)); // NOI18N
        jLabel4.setText("Верхний предел:");

        jLabel5.setFont(new java.awt.Font("Sitka Small", 0, 12)); // NOI18N
        jLabel5.setText("Нижний предел:");

        jLabel6.setFont(new java.awt.Font("Sitka Small", 0, 12)); // NOI18N
        jLabel6.setText("Шаг:");

        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jButton1.setText("Внести ");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Рассчитать");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Нижний предел", "Верхний предел", "Шаг", "Результат"
            }
        ));
        jTable1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jTable1ComponentHidden(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton3.setText("Удалить строку");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setText("Заполнить");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton5.setText("Очистить");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(57, 57, 57))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Метод для обновления таблицы из коллекции
    private void updateTableFromList() {
        tableModel.setRowCount(0);
        for (RecIntegral rec : dataList) {
            String resultStr = rec.hasResult ? 
                String.format("%.6f", rec.result) : "";
            tableModel.addRow(new Object[]{
                rec.lowerLimit,
                rec.upperLimit,
                rec.step,
                resultStr
            });
        }
    }
    
    // Метод для обновления коллекции из таблицы
    private void updateListFromTable() {
        dataList.clear();
        for (int i = 0; i < tableModel.getRowCount(); i++) {
            try {
                double lowerLimit = Double.parseDouble(
                    tableModel.getValueAt(i, 0).toString());
                double upperLimit = Double.parseDouble(
                    tableModel.getValueAt(i, 1).toString());
                double step = Double.parseDouble(
                    tableModel.getValueAt(i, 2).toString());
                
                String resultStr = tableModel.getValueAt(i, 3).toString();
                boolean hasResult = !resultStr.trim().isEmpty();
                
                RecIntegral rec;
                if (hasResult) {
                    rec = new RecIntegral(lowerLimit, upperLimit, step, 
                        Double.parseDouble(resultStr));
                } else {
                    rec = new RecIntegral(lowerLimit, upperLimit, step);
                }
                dataList.add(rec);
            } catch (NumberFormatException | NullPointerException e) {
                // Пропускаем некорректные строки
            }
        }
    }
    
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    //кнопка рассчитать
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         //int rowCount = tableModel.getRowCount();
         int selectedRow = jTable1.getSelectedRow();
         int calculatedCount = 0;
    

    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Пожалуйста, выберите строку для рассчета!", 
            "Предупреждение", 
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    } 
     
        try {
            Object lowerObj = tableModel.getValueAt(selectedRow, 0);
            Object upperObj = tableModel.getValueAt(selectedRow, 1);
            Object stepObj = tableModel.getValueAt(selectedRow, 2);
            
            if (lowerObj == null || upperObj == null || stepObj == null ||
                lowerObj.toString().trim().isEmpty() || 
                upperObj.toString().trim().isEmpty() || 
                stepObj.toString().trim().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Не все данные введены", 
                    "Информация", 
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        }
                     
            double lowerLimit = Double.parseDouble(lowerObj.toString());
            double upperLimit = Double.parseDouble(upperObj.toString());
            double step = Double.parseDouble(stepObj.toString());
                       
        Object resultValue = tableModel.getValueAt(selectedRow, 3);
        boolean hasResult = resultValue != null && !resultValue.toString().trim().isEmpty();
        
        if (hasResult) {
            int ans = javax.swing.JOptionPane.showConfirmDialog(this,
                    "В этой строке уже есть результат!Проверьте были ли изменены столбцы!Произвести расчет снова?",
                    "Подтверждение",
                    javax.swing.JOptionPane.YES_NO_OPTION);
            
            if (ans != javax.swing.JOptionPane.YES_OPTION){
                return;
            }
            //return;
        }
        
            // Вычисляем интеграл
            double result = calculateIntegral(lowerLimit, upperLimit, step);
            
            //сохранение реза
            tableModel.setValueAt(String.format("%.6f", result), selectedRow, 3);
            calculatedCount++;
            
        } catch (NumberFormatException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Ошибка формата данных в выбранной строке!", 
            "Ошибка", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Произошла ошибка при расчете!", 
            "Ошибка", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }
 
    
    }//GEN-LAST:event_jButton2ActionPerformed

    
    private void jTable1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable1ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1ComponentHidden

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //данные из полей по кнопке заполнить
        //private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
    try {
        double lowerLimit = Double.parseDouble(jTextField2.getText().trim());
        double upperLimit = Double.parseDouble(jTextField1.getText().trim());
        double step = Double.parseDouble(jTextField3.getText().trim());
        
        if (lowerLimit >= upperLimit) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Нижний предел должен быть меньше верхнего!", 
                "Ошибка", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (step <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Шаг должен быть положительным числом!", 
                "Ошибка", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Добавляем в таблицу
        tableModel.addRow(new Object[]{lowerLimit, upperLimit, step, ""});
        
        // Добавляем в коллекцию (НЕ пересоздаем всю коллекцию!)
        dataList.add(new RecIntegral(lowerLimit, upperLimit, step));
        
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        
    } catch (NumberFormatException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Пожалуйста, введите корректные числовые значения!", 
            "Ошибка ввода", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
    
    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Пожалуйста, выберите строку для удаления!", 
            "Предупреждение", 
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    tableModel.removeRow(selectedRow);//удаление строки
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (dataList.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Коллекция пуста! Нечего восстанавливать.\n\n" +
            "Чтобы добавить данные в коллекцию:\n" +
            "Заполните поля и нажмите 'Внести'\n" +
            "Или рассчитайте интеграл для существующих строк",
            "Информация",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
        return;
    }
    
    // Если в таблице уже есть данные
    if (tableModel.getRowCount() > 0) {
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
            "В таблице уже есть " + tableModel.getRowCount() + " записей!\n\n" +
            "Что вы хотите сделать?\n" +
            "'Да' - заменить текущие данные данными из коллекции\n" +
            "'Нет' - добавить данные из коллекции в конец таблицы\n" +
            "Отмена",
            "Восстановление данных",
            javax.swing.JOptionPane.YES_NO_CANCEL_OPTION);
        
        if (confirm == javax.swing.JOptionPane.CANCEL_OPTION) {
            return;
        }
        
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            // Заменяем данные
            tableModel.setRowCount(0);
            updateTableFromList();
            javax.swing.JOptionPane.showMessageDialog(this,
                "Таблица заменена данными из коллекции!\n" +
                "Записей загружено: " + dataList.size(),
                "Успех",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Добавляем данные
            int addedCount = 0;
            for (RecIntegral rec : dataList) {
                boolean exists = false;
                for (int i = 0; i < tableModel.getRowCount(); i++) {
                    try {
                        double existingLower = Double.parseDouble(
                            tableModel.getValueAt(i, 0).toString());
                        double existingUpper = Double.parseDouble(
                            tableModel.getValueAt(i, 1).toString());
                        double existingStep = Double.parseDouble(
                            tableModel.getValueAt(i, 2).toString());
                        
                        if (existingLower == rec.lowerLimit && 
                            existingUpper == rec.upperLimit && 
                            existingStep == rec.step) {
                            exists = true;
                            break;
                        }
                    } catch (Exception e) {}
                }
                
                if (!exists) {
                    String resultStr = rec.hasResult ? 
                        String.format("%.6f", rec.result) : "";
                    tableModel.addRow(new Object[]{
                        rec.lowerLimit,
                        rec.upperLimit,
                        rec.step,
                        resultStr
                    });
                    addedCount++;
                }
            }
            
            // Синхронизируем коллекцию
            updateListFromTable();
            
            javax.swing.JOptionPane.showMessageDialog(this,
                "Добавлено новых записей: " + addedCount + "\n" +
                "Всего записей в таблице: " + tableModel.getRowCount(),
                "Успех",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    } else {
        // Таблица пуста - просто восстанавливаем
        updateTableFromList();
        javax.swing.JOptionPane.showMessageDialog(this,
            "Таблица восстановлена!\n" +
            "Записей загружено: " + dataList.size(),
            "Успех",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (tableModel.getRowCount() > 0) {
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
            "Очистить таблицу?\n\n" +
            "Данные останутся в коллекции.\n" +
            "Вы сможете восстановить их кнопкой 'Заполнить'.\n\n" +
            "Продолжить?",
            "Подтверждение очистки",
            javax.swing.JOptionPane.YES_NO_OPTION);
        
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            // Очищаем таблицу
            tableModel.setRowCount(0);
            
            javax.swing.JOptionPane.showMessageDialog(this,
                "Таблица очищена!\n\n" +
                "Нажмите 'Заполнить' для восстановления данных.",
                "Успех",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Таблица уже пуста!",
            "Информация",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private double calculateIntegral(double a, double b, double h) {
    double sum = 0.0;
    double x = a;
    
    while (x < b) {
        double nextX = Math.min(x + h, b);//усечение шага
        double y1 = Math.cos(x * x);
        double y2 = Math.cos(nextX * nextX);
        sum += (y1 + y2) * (nextX - x) / 2.0;//площадь 
        x = nextX;
    }
    
    return sum;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new l2frame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
